### ISSUE TITLE
gpg environment variables

### ISSUE THREAD

**Issue by palb91** [ritze/pinentry-dmenu#1]
Hi,
Could you allow your program to check "${GNUPGHOME}" environment variable to store configuration file in a non standard directory ?
Thanks
Palb91

**Comment by ritze** [comment]
Good point. I'll implement this in the next days.

**Comment by ritze** [comment]
With the latest commit e1904c21963f97cdf625a211bf80de17df41a779 in develop GNUPGHOME will be regarded.

If all works for you I will update the master branch too.

**Comment by palb91** [comment]
Nice, and perfect responsiveness !
